"""Detection-only explicit watermark fusion service.

This service does not remove pixels.  It receives already-localized candidates
from the existing YOLO/registry branch, then adds OCR, optional CLIP gallery
retrieval, and conservative rule fusion.
"""
from __future__ import annotations

import hmac
import json
import math
import os
import re
import threading
import time
from concurrent.futures import ThreadPoolExecutor
from pathlib import Path
from typing import Any

import numpy as np
from flask import Flask, jsonify, request
from PIL import Image


MAX_UPLOAD_BYTES = int(os.getenv("WATERMARK_ENSEMBLE_MAX_BYTES", str(30 * 1024 * 1024)))
API_TOKEN = os.getenv("WATERMARK_ENSEMBLE_TOKEN", "")
OCR_ENABLED = os.getenv("WATERMARK_OCR_ENABLED", "true").lower() in {"1", "true", "yes", "on"}
CLIP_ENABLED = os.getenv("WATERMARK_RETRIEVAL_ENABLED", "true").lower() in {"1", "true", "yes", "on"}
RETRIEVAL_BACKEND = os.getenv("WATERMARK_RETRIEVAL_BACKEND", "template").lower()
CLIP_MODEL_NAME = os.getenv("WATERMARK_CLIP_MODEL", "openai/clip-vit-base-patch32")
RETRIEVAL_THRESHOLD = float(os.getenv("WATERMARK_RETRIEVAL_THRESHOLD", "0.78"))
TEMPLATE_RETRIEVAL_THRESHOLD = float(os.getenv("WATERMARK_TEMPLATE_RETRIEVAL_THRESHOLD", "0.93"))
OCR_THRESHOLD = float(os.getenv("WATERMARK_OCR_THRESHOLD", "0.40"))
YOLO_THRESHOLD = float(os.getenv("WATERMARK_YOLO_THRESHOLD", "0.35"))
GALLERY_DIR = Path(os.getenv("WATERMARK_GALLERY_DIR", str(Path(__file__).parent / "gallery")))
GALLERY_MANIFEST = GALLERY_DIR / "manifest.json"
RETRIEVAL_INDEX_DIR = Path(os.getenv("WATERMARK_RETRIEVAL_INDEX_DIR", str(Path(__file__).parent / "retrieval")))
EVIDENCE_WORKERS = max(1, int(os.getenv("WATERMARK_EVIDENCE_WORKERS", "2")))

app = Flask(__name__)
app.config["MAX_CONTENT_LENGTH"] = MAX_UPLOAD_BYTES

_ocr_engine: Any = None
_ocr_error: str | None = None
_clip_processor: Any = None
_clip_model: Any = None
_clip_error: str | None = None
_gallery: list[dict[str, Any]] | None = None
_gallery_embeddings: np.ndarray | None = None
_gallery_features: np.ndarray | None = None
_vector_index: Any = None
_vector_error: str | None = None
_ocr_lock = threading.Lock()
_clip_lock = threading.Lock()
_vector_lock = threading.Lock()
_evidence_executor = ThreadPoolExecutor(max_workers=EVIDENCE_WORKERS, thread_name_prefix="watermark-evidence")

KNOWN_PLATFORMS = {
    "gemini": "Google Gemini",
    "doubao": "豆包",
    "jimeng": "即梦AI",
    "jimeng_pill": "即梦AI",
    "samsung": "Samsung Galaxy AI",
}
PLATFORM_KEYWORDS = {
    "gemini": ("gemini", "google", "双子", "谷歌"),
    "doubao": ("豆包", "doubao", "bytedance", "字节"),
    "jimeng": ("即梦", "jimeng", "dreamina"),
    "samsung": ("samsung", "galaxy", "三星"),
}
AI_GENERATION_PHRASES = (
    "ai生成", "ai 生成", "由ai生成", "人工智能生成", "ai创作", "ai制作",
    "aigc", "ai generated", "generated by ai", "made with ai", "created with ai",
)
AI_TOKEN_PATTERN = re.compile(r"(?:^|[^a-z])ai(?:$|[^a-z])", re.IGNORECASE)
REGISTRY_TRUST_THRESHOLDS = {
    "gemini": 0.62,
    "doubao": 0.82,
    "jimeng": 0.82,
    "jimeng_pill": 1.01,
    "samsung": 0.82,
}


def _authorized() -> bool:
    if not API_TOKEN:
        return False
    header = request.headers.get("Authorization", "")
    supplied = header[7:] if header.startswith("Bearer ") else ""
    return bool(supplied) and hmac.compare_digest(supplied, API_TOKEN)


def _clamp(value: float, low: float = 0.0, high: float = 1.0) -> float:
    return float(max(low, min(high, float(value))))


def _number(value: Any, default: float = 0.0) -> float:
    try:
        number = float(value)
        return number if math.isfinite(number) else default
    except (TypeError, ValueError):
        return default


def _bbox(value: Any) -> dict[str, float] | None:
    if not isinstance(value, dict):
        return None
    x, y = _number(value.get("x")), _number(value.get("y"))
    w, h = _number(value.get("w")), _number(value.get("h"))
    if w <= 0 or h <= 0 or x < 0 or y < 0 or x + w > 1.001 or y + h > 1.001:
        return None
    return {"x": round(_clamp(x), 4), "y": round(_clamp(y), 4), "w": round(_clamp(w), 4), "h": round(_clamp(h), 4)}


def _overlap(first: dict[str, float], second: dict[str, float]) -> bool:
    ax1, ay1 = first["x"], first["y"]
    ax2, ay2 = ax1 + first["w"], ay1 + first["h"]
    bx1, by1 = second["x"], second["y"]
    bx2, by2 = bx1 + second["w"], by1 + second["h"]
    intersection = max(0.0, min(ax2, bx2) - max(ax1, bx1)) * max(0.0, min(ay2, by2) - max(ay1, by1))
    smaller = min(first["w"] * first["h"], second["w"] * second["h"])
    return smaller > 0 and intersection / smaller >= 0.45


def _position(box: dict[str, float]) -> str:
    cx, cy = box["x"] + box["w"] / 2, box["y"] + box["h"] / 2
    vertical = "top" if cy < 0.34 else "bottom" if cy > 0.66 else "middle"
    horizontal = "left" if cx < 0.34 else "right" if cx > 0.66 else "center"
    return f"{vertical}-{horizontal}"


def _position_score(box: dict[str, float]) -> float:
    position = _position(box)
    if position in {"top-left", "top-right", "bottom-left", "bottom-right"}:
        return 1.0
    if position in {"top-center", "bottom-center"}:
        return 0.70
    return 0.25


def _crop(image: Image.Image, box: dict[str, float], padding: float = 0.02) -> Image.Image:
    width, height = image.size
    x1 = max(0, int((box["x"] - padding) * width))
    y1 = max(0, int((box["y"] - padding) * height))
    x2 = min(width, int((box["x"] + box["w"] + padding) * width))
    y2 = min(height, int((box["y"] + box["h"] + padding) * height))
    return image.crop((x1, y1, max(x1 + 1, x2), max(y1 + 1, y2))).convert("RGB")


def _opacity_proxy(crop: Image.Image) -> float:
    """Estimate overlay translucency; this is a visual proxy, not alpha recovery."""
    gray = np.asarray(crop.convert("L"), dtype=np.float32)
    if gray.size < 16:
        return 0.5
    edge = np.abs(np.diff(gray, axis=0)).mean() + np.abs(np.diff(gray, axis=1)).mean()
    contrast = float(gray.std())
    # Low-contrast, low-edge marks are more consistent with translucent overlays.
    return round(_clamp(1.0 - (0.65 * min(edge / 55.0, 1.0) + 0.35 * min(contrast / 80.0, 1.0))), 3)


def _load_ocr() -> Any:
    global _ocr_engine, _ocr_error
    if _ocr_engine is not None or _ocr_error:
        return _ocr_engine
    if not OCR_ENABLED:
        _ocr_error = "disabled"
        return None
    with _ocr_lock:
        if _ocr_engine is not None or _ocr_error:
            return _ocr_engine
        try:
            from rapidocr_onnxruntime import RapidOCR

            _ocr_engine = RapidOCR()
        except Exception as exc:  # optional branch must never break the base detector
            _ocr_error = type(exc).__name__
    return _ocr_engine


def _ocr(crop: Image.Image) -> tuple[str | None, float, list[dict[str, Any]]]:
    engine = _load_ocr()
    if engine is None:
        return None, 0.0, []
    try:
        result, _elapsed = engine(np.asarray(crop))
    except Exception:
        return None, 0.0, []
    texts: list[str] = []
    confidences: list[float] = []
    items: list[dict[str, Any]] = []
    for item in result or []:
        if not isinstance(item, (list, tuple)) or len(item) < 3:
            continue
        text = str(item[1] or "").strip()
        confidence = _clamp(_number(item[2]))
        if not text or confidence < OCR_THRESHOLD:
            continue
        texts.append(text)
        confidences.append(confidence)
        items.append({"text": text, "confidence": round(confidence, 3)})
    if not texts:
        return None, 0.0, []
    return " ".join(texts)[:200], round(sum(confidences) / len(confidences), 3), items


def _load_gallery() -> list[dict[str, Any]]:
    global _gallery
    if _gallery is not None:
        return _gallery
    _gallery = []
    try:
        entries = json.loads(GALLERY_MANIFEST.read_text(encoding="utf-8"))
    except (OSError, ValueError):
        entries = []
    for entry in entries if isinstance(entries, list) else []:
        if not isinstance(entry, dict) or not entry.get("path") or not entry.get("platform"):
            continue
        path = Path(str(entry["path"]))
        if not path.is_absolute():
            path = GALLERY_DIR / path
        if path.exists():
            _gallery.append({"path": str(path), "platform": str(entry["platform"]), "label": entry.get("label") or entry["platform"]})
    return _gallery


def _load_clip() -> tuple[Any, Any]:
    global _clip_processor, _clip_model, _clip_error
    if _clip_processor is not None and _clip_model is not None:
        return _clip_processor, _clip_model
    if _clip_error or not CLIP_ENABLED or not _load_gallery():
        if not CLIP_ENABLED:
            _clip_error = "disabled"
        return None, None
    with _clip_lock:
        if _clip_processor is not None and _clip_model is not None:
            return _clip_processor, _clip_model
        try:
            from retrieval import ClipImageEncoder

            _clip_model = ClipImageEncoder(CLIP_MODEL_NAME, device=os.getenv("WATERMARK_CLIP_DEVICE", "auto"))
            _clip_processor = True
        except Exception as exc:  # retrieval is best-effort and can be disabled on small hosts
            _clip_error = type(exc).__name__
    return _clip_processor, _clip_model


def _embed(images: list[Image.Image]) -> np.ndarray | None:
    _processor, model = _load_clip()
    if processor is None or model is None or not images:
        return None
    try:
        return model.embed(images)
    except Exception as exc:
        global _clip_error
        _clip_error = type(exc).__name__
        return None


def _visual_feature(image: Image.Image) -> np.ndarray:
    resized = np.asarray(image.convert("RGB").resize((32, 32)), dtype=np.float32) / 255.0
    gray = resized.mean(axis=2)
    histograms = [np.histogram(resized[:, :, channel], bins=16, range=(0.0, 1.0), density=True)[0] for channel in range(3)]
    edge_x = np.abs(np.diff(gray, axis=1)).mean(axis=0)
    edge_y = np.abs(np.diff(gray, axis=0)).mean(axis=1)
    feature = np.concatenate([np.asarray(histograms, dtype=np.float32).ravel(), gray[::4, ::4].ravel(), edge_x, edge_y])
    norm = float(np.linalg.norm(feature))
    return feature / max(norm, 1e-8)


def _empty_retrieval(reason: str, *, backend: str | None = None) -> dict[str, Any]:
    return {
        "accepted": False,
        "platform": None,
        "candidatePlatform": None,
        "similarity": 0.0,
        "threshold": _retrieval_threshold(),
        "margin": 0.0,
        "referenceId": None,
        "referenceSource": None,
        "reason": reason,
        "backend": backend or RETRIEVAL_BACKEND,
        "topMatches": [],
    }


def _load_vector_index() -> Any:
    global _vector_index, _vector_error
    if _vector_index is not None or _vector_error:
        return _vector_index
    with _vector_lock:
        if _vector_index is not None or _vector_error:
            return _vector_index
        try:
            from retrieval import load_from_environment

            _vector_index = load_from_environment(RETRIEVAL_INDEX_DIR, CLIP_MODEL_NAME)
        except Exception as exc:
            _vector_error = f"{type(exc).__name__}:{exc}"
    return _vector_index


def _retrieve(crop: Image.Image, position: str | None = None) -> dict[str, Any]:
    global _gallery_features
    global _gallery_embeddings
    if not CLIP_ENABLED:
        return _empty_retrieval("disabled")
    if RETRIEVAL_BACKEND == "faiss_clip":
        index = _load_vector_index()
        if index is None:
            return _empty_retrieval(_vector_error or "index_unavailable")
        try:
            result = index.search(crop, position=position)
            return {**_empty_retrieval(str(result.get("reason") or "unknown")), **result, "backend": RETRIEVAL_BACKEND}
        except Exception as exc:
            return _empty_retrieval(f"query_failed:{type(exc).__name__}")
    gallery = _load_gallery()
    if not gallery:
        return _empty_retrieval("gallery_empty")
    if RETRIEVAL_BACKEND == "template":
        if _gallery_features is None:
            features = []
            for item in gallery:
                with Image.open(item["path"]) as reference:
                    features.append(_visual_feature(reference))
            _gallery_features = np.stack(features).astype(np.float32)
        query = _visual_feature(crop)
        scores = np.matmul(_gallery_features, query)
        index = int(np.argmax(scores))
        similarity = round(float(scores[index]), 4)
        threshold = _retrieval_threshold()
        accepted = similarity >= threshold
        return {
            **_empty_retrieval("accepted" if accepted else "below_platform_threshold"),
            "accepted": accepted,
            "platform": gallery[index]["platform"] if accepted else None,
            "candidatePlatform": gallery[index]["platform"],
            "similarity": similarity,
            "threshold": threshold,
            "referenceId": gallery[index].get("label"),
        }
    if RETRIEVAL_BACKEND != "clip":
        return _empty_retrieval("backend_not_supported")
    if _gallery_embeddings is None:
        references = []
        for item in gallery:
            with Image.open(item["path"]) as reference:
                references.append(reference.convert("RGB"))
        embeddings = _embed(references)
        if embeddings is None:
            return _empty_retrieval(_clip_error or "model_unavailable")
        _gallery_embeddings = embeddings
    query = _embed([crop])
    if query is None:
        return _empty_retrieval(_clip_error or "model_unavailable")
    scores = np.matmul(_gallery_embeddings, query[0])
    index = int(np.argmax(scores))
    similarity = round(float(scores[index]), 4)
    threshold = _retrieval_threshold()
    accepted = similarity >= threshold
    return {
        **_empty_retrieval("accepted" if accepted else "below_platform_threshold"),
        "accepted": accepted,
        "platform": gallery[index]["platform"] if accepted else None,
        "candidatePlatform": gallery[index]["platform"],
        "similarity": similarity,
        "threshold": threshold,
        "referenceId": gallery[index].get("label"),
    }


def _retrieval_threshold() -> float:
    if RETRIEVAL_BACKEND == "template":
        return max(RETRIEVAL_THRESHOLD, TEMPLATE_RETRIEVAL_THRESHOLD)
    return RETRIEVAL_THRESHOLD


def _retrieval_entry_count() -> int:
    if RETRIEVAL_BACKEND == "faiss_clip":
        index = _load_vector_index()
        return len(index.entries) if index is not None else 0
    return len(_load_gallery())


def _retrieval_available() -> bool:
    if not CLIP_ENABLED:
        return False
    if RETRIEVAL_BACKEND == "faiss_clip":
        return _load_vector_index() is not None
    if RETRIEVAL_BACKEND == "template":
        return bool(_load_gallery())
    return bool(_load_gallery()) and _load_clip()[1] is not None


def _keyword_platform(text: str | None) -> str | None:
    lowered = (text or "").lower()
    for platform, keywords in PLATFORM_KEYWORDS.items():
        if any(keyword.lower() in lowered for keyword in keywords):
            return KNOWN_PLATFORMS[platform]
    return None


def _analyze_text_signal(
    text: str | None,
    ocr_confidence: float,
    position_score: float,
    detection_confidence: float,
    source_platform: str | None,
) -> dict[str, Any]:
    """Interpret OCR wording as supporting evidence, never as sole provenance."""
    normalized = re.sub(r"\s+", "", (text or "")).lower()
    display_text = str(text or "").strip()
    if not display_text:
        return {
            "available": False,
            "text": None,
            "verdict": "unavailable",
            "likelyAIgenerated": False,
            "aiGenerationConfidence": 0.0,
            "matchedKeywords": [],
            "platformMatch": None,
            "interpretation": "未识别到可用于文字语义判断的内容。",
            "caveat": "文字证据不可用，不代表图片没有水印。",
        }

    matched = []
    seen_match_keys = set()
    for phrase in AI_GENERATION_PHRASES:
        match_key = phrase.replace(" ", "")
        if match_key in normalized and match_key not in seen_match_keys:
            matched.append(phrase)
            seen_match_keys.add(match_key)
    has_standalone_ai = bool(AI_TOKEN_PATTERN.search(display_text))
    if has_standalone_ai and not matched:
        matched.append("AI")
    platform_match = source_platform
    if matched and (source_platform or any(phrase != "AI" for phrase in matched)):
        confidence = 0.48 * ocr_confidence + 0.20 * position_score + 0.17 * detection_confidence + 0.15
        if source_platform:
            confidence += 0.08
        return {
            "available": True,
            "text": display_text,
            "verdict": "supports_ai_generation",
            "likelyAIgenerated": True,
            "aiGenerationConfidence": round(min(0.99, _clamp(confidence)), 3),
            "matchedKeywords": matched,
            "platformMatch": platform_match,
            "interpretation": "文字明确包含 AI 生成语义" + (f"，且匹配 {source_platform} 平台词。" if source_platform else "。"),
            "caveat": "这是显式水印文字证据，仍应与定位框、位置和其他证据一起解释。",
        }
    if source_platform:
        confidence = 0.42 * ocr_confidence + 0.20 * position_score + 0.18 * detection_confidence + 0.18
        return {
            "available": True,
            "text": display_text,
            "verdict": "supports_ai_generation",
            "likelyAIgenerated": True,
            "aiGenerationConfidence": round(min(0.92, _clamp(confidence)), 3),
            "matchedKeywords": [source_platform],
            "platformMatch": platform_match,
            "interpretation": f"文字匹配 {source_platform} 平台词，但未完整识别到“AI生成”措辞。",
            "caveat": "平台词本身是辅助证据，不能替代完整来源凭证。",
        }
    if has_standalone_ai:
        confidence = 0.28 * ocr_confidence + 0.20 * position_score + 0.12 * detection_confidence + 0.10
        return {
            "available": True,
            "text": display_text,
            "verdict": "inconclusive",
            "likelyAIgenerated": False,
            "aiGenerationConfidence": round(min(0.68, _clamp(confidence)), 3),
            "matchedKeywords": ["AI"],
            "platformMatch": None,
            "interpretation": "文字中出现 AI，但没有足够完整的生成语义或平台归属。",
            "caveat": "单独出现“AI”不能证明图片由 AI 生成。",
        }
    return {
        "available": True,
        "text": display_text,
        "verdict": "not_supported",
        "likelyAIgenerated": False,
        "aiGenerationConfidence": 0.08,
        "matchedKeywords": [],
        "platformMatch": None,
        "interpretation": "OCR 文字未显示 AI 生成语义，也未匹配已知平台词。",
        "caveat": "普通文字、字幕、签名或品牌名不能据此判定为 AI 生成。",
    }


def _ai_watermark_verdict(hits: list[dict[str, Any]]) -> dict[str, Any]:
    """Answer the product question: is this an AI-generation watermark?"""
    if not hits:
        return {
            "verdict": "no",
            "isAiGeneratedWatermark": False,
            "confidence": 0.0,
            "reason": "没有发现可用的水印候选。",
            "relevantHitCount": 0,
        }
    supporting = [
        hit for hit in hits
        if (hit.get("textAnalysis") or {}).get("verdict") == "supports_ai_generation"
        or hit.get("registryMatched") is True
        or (hit.get("type") == "logo" and hit.get("sourcePlatform"))
    ]
    if supporting:
        top = max(
            supporting,
            key=lambda hit: _number((hit.get("textAnalysis") or {}).get("aiGenerationConfidence"))
            or _number(hit.get("confidence")),
        )
        signal = top.get("textAnalysis") or {}
        confidence = _number(signal.get("aiGenerationConfidence")) or _number(top.get("confidence"))
        return {
            "verdict": "yes",
            "isAiGeneratedWatermark": True,
            "confidence": round(_clamp(confidence), 3),
            "reason": signal.get("interpretation") or "命中已知 AI 平台水印或 Logo。",
            "relevantHitCount": len(supporting),
        }
    text_hits = [hit for hit in hits if hit.get("type") == "text"]
    if text_hits and all((hit.get("textAnalysis") or {}).get("verdict") == "not_supported" for hit in text_hits):
        return {
            "verdict": "no",
            "isAiGeneratedWatermark": False,
            "confidence": 0.92,
            "reason": "候选区域中的文字未包含 AI 生成语义，已按普通文字水印过滤。",
            "relevantHitCount": 0,
        }
    return {
        "verdict": "inconclusive",
        "isAiGeneratedWatermark": None,
        "confidence": round(max((_number(hit.get("confidence")) for hit in hits), default=0.0), 3),
        "reason": "发现水印候选，但没有足够的 AI 平台、Logo 或生成语义证据。",
        "relevantHitCount": len(hits),
    }


def _fuse_candidate(image: Image.Image, raw: dict[str, Any], registry: bool = False) -> dict[str, Any] | None:
    box = _bbox(raw.get("bbox"))
    if box is None:
        return None
    detection_confidence = _clamp(_number(raw.get("confidence")))
    if not registry and detection_confidence < YOLO_THRESHOLD:
        return None
    crop = _crop(image, box)
    position = _position(box)
    ocr_future = _evidence_executor.submit(_ocr, crop)
    retrieval_future = _evidence_executor.submit(_retrieve, crop, position)
    text, ocr_confidence, ocr_items = ocr_future.result()
    retrieval = retrieval_future.result()
    retrieval_platform = retrieval.get("platform")
    retrieval_similarity = _number(retrieval.get("similarity"))
    retrieval_accepted = retrieval.get("accepted") is True
    ocr_platform = _keyword_platform(text)
    if not retrieval_accepted and ocr_platform:
        corroborating = (retrieval.get("platformScores") or {}).get(ocr_platform) or {}
        corroborating_similarity = _number(corroborating.get("similarity"))
        corroborating_threshold = _number(corroborating.get("threshold"), 1.01)
        if corroborating_similarity >= corroborating_threshold and corroborating.get("positionMatch") is True:
            retrieval_accepted = True
            retrieval_platform = ocr_platform
            retrieval_similarity = corroborating_similarity
            retrieval = {
                **retrieval,
                "accepted": True,
                "platform": ocr_platform,
                "similarity": corroborating_similarity,
                "threshold": corroborating_threshold,
                "referenceId": corroborating.get("referenceId"),
                "referenceSource": corroborating.get("referenceSource"),
                "reason": "accepted_with_ocr_corroboration",
            }
    provider = str(raw.get("provider") or "")
    registry_provenance = raw.get("corroborated") is True
    yolo_corroborated = raw.get("_yoloCorroborated") is True
    registry_trusted = bool(
        registry
        and provider != "jimeng_pill"
        and (
            registry_provenance
            or (
                yolo_corroborated
                and detection_confidence >= REGISTRY_TRUST_THRESHOLDS.get(provider, 1.01)
            )
        )
    )
    known_platform = KNOWN_PLATFORMS.get(provider) if registry_trusted else None
    retrieval_threshold = _number(retrieval.get("threshold"), _retrieval_threshold())
    source_platform = known_platform or ocr_platform or (
        retrieval_platform if retrieval_accepted else None
    )
    area_ratio = round(box["w"] * box["h"], 5)
    position_score = _position_score(box)
    size_score = _clamp(1.0 - abs(math.log10(max(area_ratio, 1e-5)) + 2.0) / 2.0)
    opacity_proxy = _opacity_proxy(crop)
    text_signal = _analyze_text_signal(
        text,
        ocr_confidence,
        position_score,
        detection_confidence,
        source_platform if text else None,
    )
    if text and ocr_confidence >= OCR_THRESHOLD:
        watermark_type = "text"
        confidence = 0.45 * detection_confidence + 0.30 * ocr_confidence + 0.15 * position_score + 0.10 * size_score
        reasons = ["候选框与OCR文字重叠"]
        if source_platform:
            reasons.append("文字与已知平台关键词匹配")
    elif known_platform or retrieval_accepted:
        watermark_type = "logo"
        confidence = 0.45 * detection_confidence + 0.30 * max(retrieval_similarity, 0.65) + 0.15 * position_score + 0.10 * size_score
        reasons = ["候选框内未识别到可靠文字", "检索库相似度、平台差距和位置校验均通过" if retrieval_accepted else "平台注册表与定位模型交叉确认"]
    else:
        watermark_type = "unknown"
        # Unknown is intentionally capped: localization alone is not platform attribution.
        confidence = min(0.79, 0.60 * detection_confidence + 0.20 * position_score + 0.10 * size_score)
        reasons = ["候选框由水印定位模型发现", "OCR未形成可靠文字证据", "图库相似度未达到已知平台阈值"]
    confidence = round(_clamp(confidence), 3)
    return {
        "bbox": box,
        "type": watermark_type,
        "text": text,
        "sourcePlatform": source_platform,
        "detectionConfidence": round(detection_confidence, 3),
        "ocrConfidence": round(ocr_confidence, 3),
        "ocrItems": ocr_items,
        "textAnalysis": text_signal,
        "retrievalSimilarity": round(retrieval_similarity, 4),
        "retrievalAccepted": retrieval_accepted,
        "retrievalThreshold": round(retrieval_threshold, 4),
        "retrievalMargin": round(_number(retrieval.get("margin")), 4),
        "retrievalMinimumMargin": round(_number(retrieval.get("minimumMargin")), 4),
        "retrievalCandidatePlatform": retrieval.get("candidatePlatform"),
        "retrievalReferenceId": retrieval.get("referenceId"),
        "retrievalReferenceSource": retrieval.get("referenceSource"),
        "retrievalReason": retrieval.get("reason"),
        "retrievalBackend": retrieval.get("backend") or RETRIEVAL_BACKEND,
        "retrievalTopMatches": retrieval.get("topMatches") or [],
        "retrievalError": None if retrieval.get("reason") in {"accepted", "accepted_with_ocr_corroboration", "below_platform_threshold", "ambiguous_platform_margin", "position_mismatch"} else retrieval.get("reason"),
        "position": position,
        "areaRatio": area_ratio,
        "opacityEstimate": opacity_proxy,
        "confidence": confidence,
        "confidenceBand": "high" if confidence >= 0.80 else "medium" if confidence >= 0.60 else "low",
        "reason": reasons,
        "providerHint": provider or None,
        "registryCandidate": registry,
        "registryMatched": registry_trusted,
        "registryProvenance": registry_provenance,
        "yoloCorroborated": yolo_corroborated,
    }


def _merge_candidates(candidates: list[Any], registry_hits: list[Any]) -> list[dict[str, Any]]:
    merged: list[dict[str, Any]] = []
    for item in registry_hits:
        if isinstance(item, dict) and _bbox(item.get("bbox")):
            item_box = _bbox(item.get("bbox"))
            corroborating = [
                candidate
                for candidate in candidates
                if isinstance(candidate, dict)
                and _bbox(candidate.get("bbox"))
                and _overlap(item_box, _bbox(candidate.get("bbox")))
            ]
            best_yolo = max(corroborating, key=lambda candidate: _number(candidate.get("confidence")), default=None)
            merged.append({
                **item,
                "_registry": True,
                "_yoloCorroborated": best_yolo is not None,
                "_yoloConfidence": _number(best_yolo.get("confidence")) if best_yolo else 0.0,
            })
    for item in candidates:
        if not isinstance(item, dict) or not _bbox(item.get("bbox")):
            continue
        if any(_overlap(_bbox(item["bbox"]), _bbox(existing["bbox"])) for existing in merged):
            continue
        merged.append(item)
    return merged[:32]


def analyze(image: Image.Image, candidates: list[Any], registry_hits: list[Any]) -> dict[str, Any]:
    started = time.perf_counter()
    hits = []
    for raw in _merge_candidates(candidates, registry_hits):
        hit = _fuse_candidate(image, raw, registry=bool(raw.get("_registry")))
        if hit:
            hits.append(hit)
    hits.sort(key=lambda item: item["confidence"], reverse=True)
    top = hits[0] if hits else None
    text_signals = [
        hit["textAnalysis"]
        for hit in hits
        if isinstance(hit.get("textAnalysis"), dict) and hit["textAnalysis"].get("available")
    ]
    strongest_text_signal = max(
        text_signals,
        key=lambda item: _number(item.get("aiGenerationConfidence")),
        default=None,
    )
    ai_generation_text_signal = strongest_text_signal or {
        "available": False,
        "text": None,
        "verdict": "unavailable",
        "likelyAIgenerated": False,
        "aiGenerationConfidence": 0.0,
        "matchedKeywords": [],
        "platformMatch": None,
        "interpretation": "当前没有可用的 OCR 文字内容。",
        "caveat": "未识别到文字不等于没有显式水印。",
    }
    ai_watermark_verdict = _ai_watermark_verdict(hits)
    return {
        "detected": bool(hits),
        "type": top["type"] if top else "none",
        "sourcePlatform": top["sourcePlatform"] if top else None,
        "confidence": top["confidence"] if top else 0.0,
        "confidenceBand": top["confidenceBand"] if top else "low",
        "hits": hits,
        "aiWatermarkVerdict": ai_watermark_verdict,
        "aiGenerationTextSignal": ai_generation_text_signal,
        "fusion": {
            "candidateCount": len(candidates),
            "registryCount": len(registry_hits),
            "ocr": {"enabled": OCR_ENABLED, "available": _load_ocr() is not None, "error": _ocr_error},
            "retrieval": {
                "enabled": CLIP_ENABLED,
                "galleryCount": _retrieval_entry_count(),
                "available": _retrieval_available(),
                "backend": RETRIEVAL_BACKEND,
                "model": CLIP_MODEL_NAME,
                "threshold": _retrieval_threshold(),
                "error": _vector_error or _clip_error,
            },
            "rule": "candidate + OCR + calibrated FAISS retrieval + platform margin + position + registry provenance; unknown is not forced to a platform",
        },
        "elapsedMs": int((time.perf_counter() - started) * 1000),
        "coordinateSpace": "display_normalized_v1",
        "mode": "detect-only",
    }


@app.get("/health")
def health():
    return {
        "available": bool(API_TOKEN),
        "status": "ok" if API_TOKEN else "degraded",
        "mode": "detect-only",
        "tokenReady": bool(API_TOKEN),
        "ocr": {"enabled": OCR_ENABLED, "available": _load_ocr() is not None, "error": _ocr_error},
        "retrieval": {"enabled": CLIP_ENABLED, "galleryCount": _retrieval_entry_count(), "available": _retrieval_available(), "backend": RETRIEVAL_BACKEND, "model": CLIP_MODEL_NAME, "threshold": _retrieval_threshold(), "error": _vector_error or _clip_error},
        "coordinateSpace": "display_normalized_v1",
    }


@app.post("/v1/analyze")
def analyze_route():
    if not _authorized():
        return jsonify({"detail": "unauthorized"}), 401
    uploaded = request.files.get("file")
    if uploaded is None or not uploaded.filename:
        return jsonify({"detail": "file is required"}), 400
    data = uploaded.stream.read(MAX_UPLOAD_BYTES + 1)
    if not data:
        return jsonify({"detail": "empty file"}), 400
    if len(data) > MAX_UPLOAD_BYTES:
        return jsonify({"detail": "file too large"}), 413
    try:
        image = Image.open(__import__("io").BytesIO(data)).convert("RGB")
        candidates = json.loads(request.form.get("candidates", "[]"))
        registry_hits = json.loads(request.form.get("registryHits", "[]"))
        if not isinstance(candidates, list) or not isinstance(registry_hits, list):
            raise ValueError("candidate_schema_invalid")
        result = analyze(image, candidates, registry_hits)
        return {"status": "ok", "explicitWatermark": result, "visibleHits": result["hits"]}
    except Exception as exc:
        app.logger.exception("watermark ensemble failed")
        return jsonify({"detail": "ensemble failed", "errorType": type(exc).__name__}), 422


@app.errorhandler(413)
def too_large(_error):
    return jsonify({"detail": "file too large"}), 413
