-- Two-person governance for records created before immutable account ownership.
CREATE TABLE IF NOT EXISTS `legacy_record_governance` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `request_operation_id` CHAR(36) NOT NULL,
  `record_type` VARCHAR(16) NOT NULL,
  `record_id` BIGINT NOT NULL,
  `record_fingerprint` CHAR(64) NOT NULL,
  `media_sha256` CHAR(64) NOT NULL,
  `active_record_key` VARCHAR(64) NULL,
  `status` VARCHAR(24) NOT NULL DEFAULT 'claim_pending',
  `target_account_uuid` CHAR(36) NOT NULL,
  `target_user_id` BIGINT NOT NULL,
  `target_account_fingerprint` CHAR(64) NOT NULL,
  `evidence_reference` VARCHAR(512) NOT NULL,
  `evidence_sha256` CHAR(64) NOT NULL,
  `reason` VARCHAR(1000) NOT NULL,
  `requester_admin_id` BIGINT NOT NULL,
  `requester_username` VARCHAR(64) NOT NULL,
  `requester_identity_hash` CHAR(64) NOT NULL,
  `request_integrity_hmac` CHAR(64) NOT NULL,
  `requested_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `approval_operation_id` CHAR(36) NULL,
  `approver_admin_id` BIGINT NULL,
  `approver_username` VARCHAR(64) NULL,
  `approver_identity_hash` CHAR(64) NULL,
  `approval_integrity_hmac` CHAR(64) NULL,
  `decision_reason` VARCHAR(1000) NULL,
  `audit_key_id` VARCHAR(64) NOT NULL,
  `approved_at` DATETIME NULL,
  `version` INT NOT NULL DEFAULT 1,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_legacy_request_operation` (`request_operation_id`),
  UNIQUE KEY `uk_legacy_active_record` (`active_record_key`),
  UNIQUE KEY `uk_legacy_approval_operation` (`approval_operation_id`),
  KEY `idx_legacy_status_requested` (`status`, `requested_at`),
  KEY `idx_legacy_target_account` (`target_account_uuid`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='历史遗留记录双人认领治理台账';
